version: '3.8'

services:
  ethereum-blocks:
    image: busybox
    container_name: ethereum-blocks
    ports:
      - "9997:80"
    volumes:
      - ./:/var/www:ro
    command: httpd -f -p 80 -h /var/www
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 1s
 